name: Deploy Jekyll to Public Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4

      - name: Setup Ruby and Jekyll
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --destination ./_site

      - name: Push Built Site to Public Repo
        run: |
          git clone https://github.com/ankushgpta2/latentmap.io.deploy.git public-repo
          rm -rf public-repo/*
          cp -r _site/* public-repo/
          cd public-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Jekyll site"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/ankushgpta2/latentmap.io.deploy.git main
